export function makePrompt(session, job) {
  const schema = {
    jobId: job.id,
    kind: job.kind === 'requirements' ? 'questions' : `${job.kind}_complete`,
    message: 'Human-readable progress or completion summary',
    questions: ['A question for the human, when clarification is needed'],
    requirements: 'Full requirements in Markdown when ready',
    assessment: { feasible: true, evidence: 'Files inspected and checks performed, results and remaining risks', steps: ['Short ordered implementation step'], technologies: ['Technology and why it fits'], codeImpact: ['Existing files/interfaces/data affected, compatibility and migration impact; or new project'] },
    uiChanged: false,
    impact: [{ file: 'src/example.js', description: 'What changed and why' }],
    tests: ['Commands run and actual results; clearly identify anything not run'],
    findings: ['Actionable issue with file/location, evidence and required fix; empty only when every check passed'],
    checks: Object.fromEntries(['features', 'readability', 'formatting', 'tests', 'architecture'].map(key => [key, { passed: false, evidence: 'Actual inspection or command and result' }])),
    addressedFindings: ['Review finding, change made and verification result']
  };
  return `You are working in a ${session.execution?.backend === 'docker-linux' ? 'Linux Docker container workspace at /workspace, with VS Code on the Windows host' : 'Windows workspace'} managed by AI Workbench.
Use VS Code local agent tools to work in this folder. Never use Copilot CLI.
${session.execution?.backend === 'docker-linux' ? 'Run ALL dependency installation, application commands, builds, tests, probes and browser demos inside this workspace container using the attached Dev Container terminal. Paths inside the container are Linux paths; never use the Windows host folder for execution. If the window is not attached yet, ask the human to use Open VS Code in the dashboard. Do not fall back to running generated code on the host. Node.js 22, npm, Git, Playwright and Chromium are preinstalled. Configure demo start commands for Linux executables and arguments. Demo localhost refers to this container. Keep artifacts, response and progress files in the mounted /workspace folder.\n' : ''}
For browser feasibility run node .harness/demo/check.mjs from the workspace root. It loads the saved browser cache from .harness/demo/runtime.json before importing Playwright. A plain Playwright import in an old terminal may use a different cache; do not infer a missing browser from that alone. New VS Code terminals also receive the configured cache.
Read REQUIREMENTS.md and .harness/conversation.json for the complete brief and human answers.
Human questions must use the normal response JSON with kind="questions" and questions[] as your LAST action, then end this request immediately. Never wait for answers in VS Code chat or continue editing after asking. The dashboard collects answers and starts a new request with the saved conversation. As a LAST RESORT only, if you accidentally ask with VS Code's native question tool or end with chat-only questions, a Local hook recovers the questions into that same JSON reply and stops this request. Do not rely on the fallback; it must never replace the normal structured reply flow. Tool auto-approval does not answer human questions or approve requirements/results.
Current phase: ${job.kind}. Job ID: ${job.id}.
${job.resumeFrom ? `This request resumes interrupted work from job ${job.resumeFrom}. Preserve the existing project and completed changes. Read .harness/progress/${job.resumeFrom}.json if present, the saved conversation, REQUIREMENTS.md and existing source files. Inspect actual current state and rerun relevant checks before deciding what remains. Continue the same phase; do not recreate the project or assume the interrupted job completed. Use only this new job's response and progress paths.\n` : ''}
${job.kind === 'pr_review' ? `Perform a local PR review of the current code against every acceptance criterion in REQUIREMENTS.md. Do not edit source files. Verify all features are implemented, code is clean and human readable, naming and responsibilities are clear, formatting is consistent, and onion architecture keeps domain/application logic independent of infrastructure and presentation. Inspect code and demo artifacts, run the full applicable test suites, build, lint and formatting checks using the project's existing tools. Detect regressions and missing tests. Report exact commands and actual outcomes; a skipped, unavailable or failing required check cannot pass. Return kind="pr_review_complete" with findings[], tests[] and checks for features, readability, formatting, tests, architecture, each with passed:boolean and nonempty evidence. Include actionable findings for every failed or unverified check and any additional issue. An empty findings array is allowed only after all checks pass. Review afresh after refactoring, including prior findings and newly introduced issues. Previous findings: ${JSON.stringify(session.reviewFindings || [])}. Do not push Git or create an external PR.` : job.kind === 'refactoring' ? `Refactor and clean up the code, fixing every issue from the latest PR review: ${JSON.stringify(session.reviewFindings || [])}. Preserve approved behavior and implement missing approved features. Use clean, human readable code and consistent formatting. Apply onion architecture appropriate to the project: domain at the center, application use cases depending inward, infrastructure and presentation as outer adapters; keep external dependencies out of domain logic. Avoid unnecessary layers or abstractions. Fix regressions, failing checks and missing test coverage. Run the applicable full test suites, build, lint and formatting checks and report actual outcomes. Validate affected UI interactions with the existing browser tools when needed; prior demo artifacts predate these changes. If blocked by a decision or environment, return questions rather than claim completion. Return kind="refactoring_complete" with addressedFindings[] explaining each fix and validation, uiChanged:boolean, impact[] and nonempty tests[]. A fresh PR review runs next and determines whether any further work remains. Do not push Git or create an external PR.` : ''}
${['pr_review', 'refactoring'].includes(job.kind) ? '' : job.kind === 'demo_review' ? 'Review the latest artifacts (screenshots, demo result JSON, logs and impact reports) and compare with REQUIREMENTS.md. Check that recorded steps actually exercise the core interaction, including keyboard inputs for keyboard-controlled apps, and that screenshots show its result. A ready screen or idle animation is not proof of gameplay or interaction; return rollback if the walkthrough omits the core flow. Do not claim you watched a video unless a tool actually supports it. Do not edit source files in this phase. If bugs or unresolved implementation questions are found, return kind="rollback" with a concise message describing evidence and required fixes; this reopens development. If human input is needed return questions. Otherwise return kind="demo_review_complete" with a short message stating what was checked and any limitations.' : job.kind === 'requirements'
    ? 'Persist until requirements are complete and demonstrably feasible. Inspect the existing code, dependencies and runtime before proposing a solution. Verify feature feasibility with relevant read-only checks or small disposable probes. Document actual evidence, risks and unknowns; do not invent verification. Ask focused follow-up questions in batches until material ambiguities and blockers are resolved. Do not ask again about decisions already answered in the conversation. If infeasible, explain the blocker and ask about achievable alternatives; never mark it ready. Provide short bullet points for ordered implementation steps, technologies with reasons, and impact on existing code, interfaces, data, compatibility and tests (explicitly state if this is a new project). Organize REQUIREMENTS.md into two clearly separated sections: # Business requirements (plain language for nontechnical readers: goal, user behavior, scope, acceptance criteria and assumptions) and # Technical details (implementation steps, technologies, feasibility evidence and code impact). Keep filenames, packages, commands and architecture in Technical details. Include the technical plan in the structured assessment field. Do not develop yet. When sufficiently clear, return kind="requirements_ready" and the full Markdown requirements, including acceptance criteria, scope, constraints, and assumptions.'
    : 'Implement the approved REQUIREMENTS.md. Work autonomously within its scope. You may ask the human questions using kind="questions". Run relevant validation and report real outcomes. On completion use kind="development_complete". Write message as a concise summary for the human: what they can now do, what was checked, and any remaining limitations. This message appears beside the demo; keep file inventories and technical detail in impact[] and tests[]. Describe backend impact in impact[] and tests[]. Set uiChanged=true if any visible UI changed. If UI changed, configure .harness/demo/config.json with the local app URL, a command and args to start the app (or null if already running), and meaningful demo steps. Playwright is already installed in .harness/demo: do not install it. Demo steps support goto(path), click(selector,position optional {x,y} for canvases), fill(selector,value), press(key,selector optional,repeat optional,intervalMs optional), expect(selector,text optional), screenshot(name), and wait(milliseconds). press sends real browser keyboard events (for example key="Space", repeat=30, intervalMs=450); selector focuses an element before pressing, otherwise input goes to the page. Repeats are spaced without extra per-step pauses. Tune timing to the actual app. Configure minimumDurationMs (default 15000, maximum 60000) for a readable walkthrough. Demonstrate the core user flow with actual inputs and before/after screenshots; an idle title screen or animation alone is insufficient for an interactive app. For games, start play, send controls over several seconds, and capture gameplay plus a visible result or restart. Assert observable results with expect where available; canvas screenshots alone do not prove gameplay succeeds. Do not change app behavior to autoplay just to create a demo. Use browser selectors for your app. Do not execute the demo; the server does that.'}
Throughout work, update .harness/progress/${job.id}.json with {"jobId":"${job.id}","text":"Inspected existing files; browser check passed. Next: clarify the remaining requirement."}. Write an initial note and update after meaningful actions, roughly every 30 seconds while working. Name actual file reads/writes, endpoint calls with their HTTP methods, scope or context changes, environment modifications and any security-sensitive actions, so history can estimate A–F risk. State actions and results directly, without introductions such as "Only changes since the previous note". Do not repeat the brief or unchanged findings. Only report observable work, never private chain-of-thought or secrets. If blocked, report the blocker immediately. The server collects these notes for history.
If a development task reveals requirements need correction, return kind="rollback" with message explaining the issue as your last action; the harness reopens requirements for human approval. Do not keep editing after this response. Review prior demo failures and human feedback in the conversation when repairing a feature.
Respond to the harness by writing valid JSON to .harness/responses/${job.id}.json as your LAST action. This is the reply channel; a chat-only response cannot advance the workflow. Do not change session.json, bridge.json, jobs, or server credentials. The reply schema is:
${JSON.stringify(schema, null, 2)}
Only include applicable fields. For questions, kind="questions", questions must be nonempty. For requirements_ready include requirements, assessment (feasible=true, nonempty evidence, steps[], technologies[], codeImpact[]) and no questions. For development_complete include message, uiChanged, impact, tests. For pr_review_complete include findings, checks, tests. For refactoring_complete include addressedFindings, uiChanged, impact, tests. Use this exact jobId. Never claim work or tests were completed unless they were.
Human brief: ${session.brief}
`;
}
